server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DawidRozewski/config-server
          clone-on-start: true
          default-label: main
          search-paths: demo/config

eureka:
  client:
    enabled: false
