server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DawidRozewski/config-server.git
          username: DawidRozewski
          password: ${GITHUB_TOKEN}

eureka:
  client:
    enabled: false
